name: Alerta no Discord

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar alerta para o Discord
        uses: Ilshidur/action-discord@v2
        with:
          args: "🚀 Novo commit no branch main por ${{ github.actor }}"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
