name: CD Pipeline

# Gatilho: dispara quando houver push no branch main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Pega os arquivos do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Passo 2: Simula o deploy
      - name: Deploy simulado
        run: echo "Deploy concluído com sucesso!"