name: CI/CD com Docker e Testes

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar Main.java
        run: javac Main.java

      - name: Compilar testes com JUnit
        run: javac -cp ".:lib/junit-platform-console-standalone-1.9.2.jar" MainTest.java

      - name: Rodar testes unitários
        run: java -jar lib/junit-platform-console-standalone-1.9.2.jar --class-path . --scan-class-path

      - name: Build Docker image
        run: docker build -t minha-app .

      - name: Testar container
        run: docker run --rm minha-app