name: CI/CD Pipeline

# Dispara quando houver push nos branches main ou feature1
on:
  push:
    branches:
      - main
      - feature1

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Pega os arquivos do repositório
      - uses: actions/checkout@v4

      # Passo 2: Compila o Main.java
      - name: Compilar Java
        run: javac Main.java

      # Passo 3: Roda o Main.java
      - name: Rodar aplicação
        run: java Main

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build   # Só roda se o build passar
    steps:
      # Passo 1: Pega os arquivos do repositório novamente
      - uses: actions/checkout@v4

      # Passo 2: Simula o deploy
      - name: Deploy simulado
        run: echo "Deploy concluído com sucesso!"