name: CI Pipeline

on:
  push:
    branches: [ main, develop, feature1 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configura Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compila o projeto
        run: javac Main.java

      - name: Testa a aplicação
        run: java Main