name: CI/CD com Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Java
        run: javac Main.java

      - name: Testar execução
        run: java Main

      - name: Build Docker image
        run: docker build -t minha-app .

      - name: Testar container
        run: docker run --rm minha-app